apiVersion: aiven.io/v1alpha1
kind: PostgreSQL
metadata:
  name: pg-sample-sebi-k8s-live-coding
spec:

  # gets the authentication token from the `aiven-token` secret
  authSecretRef:
    name: aiven-token
    key: token

  # outputs the PostgreSQL connection on the `pg-connection` secret
  connInfoSecretTarget:
    name: pg-connection

  # add your Project name here
  project: dev-sandbox

  # cloud provider and plan of your choice
  # you can check all of the possibilities here https://aiven.io/pricing
  cloudName: google-europe-west1
  plan: startup-4

  # general Aiven configuration
  maintenanceWindowDow: friday
  maintenanceWindowTime: 23:00:00

  # specific PostgreSQL configuration
  userConfig:
    pg_version: '11'
